### PR TITLE
Updated M7 of 2007 other sites (#58)

### LINKED ISSUE #58: Updates to 2007 Other sites M7 rules
"M7: Bilateral epithelial tumors (8000-8799) of the ovary within 60 days are a single primary. Exception: Per SINQ20100010, this rule does not apply to tumors of different histologies." These cases won't stop at M7 so this would be visible in the rule list but not the rule stopped at.

### PR DESCRIPTION
**Pull request by bekeles**
- The 2018 rules are copy of the 2007 rules with few modifications.
- The unit tests for the 2018 rules were not really testing the 2018 rules.

Closes #58

### CODE REVIEW

**Comment by depryf** [comment]
@bekeles I merged this but I just realized there was no entry in the changelog. Didn't it need one?

**Comment by bekeles** [comment]
The merge request you merged yesterday had the change log. This was just part of that issue.

**Comment by depryf** [comment]
OK. I just didn't know if the last changes had been released already, in which case these would need to go to under a new version.

But if I merged the previous changes yesterday, then they have not been released yet.

Seems we are good.

**Comment by bekeles** [comment]
Yeap it is all good.

**Pull request merged**
